In [1]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("data\Housing.csv")
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [5]:
df.head(15)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished
10,9800000,13200,3,1,2,yes,no,yes,no,yes,2,yes,furnished
11,9681000,6000,4,3,2,yes,yes,yes,yes,no,2,no,semi-furnished
12,9310000,6550,4,2,2,yes,no,no,no,yes,1,yes,semi-furnished
13,9240000,3500,4,2,2,yes,no,no,yes,no,2,no,furnished
14,9240000,7800,3,2,2,yes,no,no,no,no,0,yes,semi-furnished

In [54]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [49]:
X

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [14]:
from sklearn.preprocessing import OrdinalEncoder

In [61]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size = 0.2 , random_state = 0)

In [ ]:
X_train

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
542,3620,2,1,1,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0
496,4000,2,1,1,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0
484,3040,2,1,1,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
507,3600,2,1,1,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0
252,9860,3,1,1,1.0,0.0,0.0,0.0,0.0,0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
70,4000,3,2,2,1.0,0.0,1.0,0.0,1.0,0,1.0,1.0
277,10360,2,1,1,1.0,0.0,0.0,0.0,0.0,1,1.0,1.0
9,5750,3,2,4,1.0,1.0,0.0,0.0,1.0,1,1.0,0.0
359,3600,3,1,1,1.0,0.0,0.0,0.0,0.0,1,0.0,0.0
192,6600,3,1,1,1.0,1.0,1.0,0.0,0.0,0,1.0,2.0

In [25]:
cat_cols = ['furnishingstatus','mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']

In [26]:
oe = OrdinalEncoder(categories=[['unfurnished','semi-furnished','furnished'],
['no','yes'],
['no','yes'],
['no','yes'],
['no','yes'],
['no','yes'],
['no','yes'],
])

In [62]:
oe.fit(X_train[cat_cols])

OrdinalEncoder(categories=[['unfurnished', 'semi-furnished', 'furnished'],
                           ['no', 'yes'], ['no', 'yes'], ['no', 'yes'],
                           ['no', 'yes'], ['no', 'yes'], ['no', 'yes']])

In [63]:
X_train[cat_cols] = oe.transform(X_train[cat_cols])
X_test[cat_cols] = oe.transform(X_test[cat_cols])

In [65]:
X_train.head(10)

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
542,3620,2,1,1,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0
496,4000,2,1,1,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0
484,3040,2,1,1,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
507,3600,2,1,1,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0
252,9860,3,1,1,1.0,0.0,0.0,0.0,0.0,0,0.0,1.0
263,3968,3,1,2,0.0,0.0,0.0,0.0,0.0,0,0.0,1.0
240,3840,3,1,2,1.0,0.0,0.0,0.0,0.0,1,1.0,1.0
175,9800,4,2,2,1.0,1.0,0.0,0.0,0.0,2,0.0,1.0
385,3640,2,1,1,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0
374,3520,2,2,1,1.0,0.0,1.0,0.0,0.0,0,0.0,1.0

In [66]:
X_test.head(10)

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
239,4000,3,1,2,1.0,0.0,0.0,0.0,0.0,1,0.0,2.0
113,9620,3,1,1,1.0,0.0,1.0,0.0,0.0,2,1.0,2.0
325,3460,4,1,2,1.0,0.0,0.0,0.0,1.0,0,0.0,1.0
66,13200,2,1,1,1.0,0.0,1.0,1.0,0.0,1,0.0,2.0
479,3660,4,1,2,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
103,6350,3,2,3,1.0,1.0,0.0,0.0,1.0,0,0.0,2.0
386,3850,3,1,1,1.0,0.0,0.0,0.0,0.0,2,0.0,0.0
480,3480,3,1,2,0.0,0.0,0.0,0.0,0.0,1,0.0,1.0
400,3512,2,1,1,1.0,0.0,0.0,0.0,0.0,1,1.0,0.0
37,9000,4,2,4,1.0,0.0,0.0,0.0,1.0,2,0.0,2.0

In [67]:
from sklearn.linear_model import LinearRegression 
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [70]:
y_pred = model.predict(X_test)
y_pred

array([ 4019080.69890147,  6258021.768564  ,  4392719.13411048,
        7335082.21688194,  2892857.56615675,  7084655.57701774,
        3258634.73504731,  3196499.16068631,  3520106.01134941,
        8359610.28845465,  6646926.36096856,  3788844.63269237,
        3734072.96467981,  4616010.40973202,  3946124.94405792,
        2023177.4684687 ,  3975554.48783028,  3624716.9650089 ,
        3210282.74216168,  4668411.38105794,  5893719.66376515,
        6415683.83807236,  4657036.55831934,  2704096.11205267,
        5356909.8618145 ,  5740682.56798041,  5337586.47961082,
        5444859.96648235,  5702144.57144374,  5865872.30432732,
        3307327.30668416,  6299491.02684292,  7123479.95544322,
        2960326.86653052,  4424323.19483818,  5125081.85591294,
        4947693.93115736,  3629027.81981122,  2975421.52734786,
        3975089.54021919,  8106313.95534003,  5014658.87529549,
        6469749.69804857,  3566139.31348661,  3868652.86219465,
        6344993.74699857,  4482572.73153155,  2740240.0896807 ,
        4105384.15298296,  6518557.36176521,  3976558.93952635,
        7056307.68945588,  2586714.16696756,  2947687.80114418,
        3553624.39318115,  5151386.47910423,  7171548.10937836,
        4052242.7088535 ,  2884254.74264866,  4379165.55939617,
        6066225.12442545,  6751773.91534441,  3382551.41414111,
        7251896.59353497,  2681431.47017135,  5138914.7819742 ,
        6685740.04693819,  2619223.8524795 ,  3824989.41251459,
        4995902.7824292 ,  4352358.99961469,  7264572.3528292 ,
        5150347.40449781,  5947769.21201797,  4086573.0979757 ,
        4549426.52941342,  2958392.04612462,  7660252.98149768,
        2656282.61262027,  3679497.40060293,  4352358.99961469,
        5981887.99426369,  5132525.06975503,  5458725.16176889,
        3822006.6426444 ,  4128176.81504507,  4698794.75914506,
        5027920.2150587 ,  3913610.13040526,  4296868.64305712,
        3290316.24497529,  5880621.00664528,  3150060.86792802,
        3668445.62490134,  4539382.03106222, 10575679.21780643,
        2971774.44221851,  7093653.99925704,  4418061.7711239 ,
        4577913.07853262,  6542179.32091921,  3322929.37680987,
        4620712.65928556,  3364236.62346778,  7400967.88555256,
        5138942.23888226,  4058811.42233283,  4972825.57184573,
        6367950.02587764])

In [71]:
y_test

239    4585000
113    6083000
325    4007500
66     6930000
479    2940000
        ...
76     6650000
132    5810000
311    4123000
464    3080000
155    5530000
Name: price, Length: 109, dtype: int64

In [72]:
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score

In [73]:
print("MAE:",mean_absolute_error(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))
print("R2 Score:",r2_score(y_test,y_pred))

MAE: 716583.4396615473
MSE: 986041803890.0277
R2 Score: 0.6578047592637593